routes/web.php
<?php

/*=== Authentication ===*/
Auth::routes();

Route::get('/', 'HomeController@index');

/*=== Auth User ===*/
Route::get('auth-users', 'HomeController@index')->name('auth-user');
Route::post('user/store', 'AuthUser\AuthUserController@store');

/*=== User ===*/
Route::get('users', 'User\UserController@index')->name('users');
Route::get('users/detail/{uid}' , 'User\UserController@detail');

/*=== Live Chat ===*/
Route::get('conversations', 'Conversation\ConversationController@index')->name('conversations');

app/AuthUser.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class AuthUser extends Eloquent implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    use Notifiable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $collection = 'auth_users';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = '_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'privilage', 'created_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function createAuthUser($name, $email, $privilage, $password)
    {
        $user = new AuthUser();
        $user->name = $name;
        $user->email = $email;
        $user->privilage = $privilage;
        $user->password = bcrypt($password);

        $user->save();
    }
}

app/Helpers.php
<?php

/*=== MenuClass ===*/
function adminMenuClass($name, $path)
{
    $path = str_replace('admin/', '', $path);

    if ($path == $name)
        return 'active';

    return '';
}

app/LinebotLog.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use App\User;

class LinebotLog extends Eloquent
{
    protected $collection = 'linebot_logs';

    function user() {
    	return $this->belongsTo('App\User', 'destination.destinationId', 'line_mid');
    }

    public function getUserIdAttribute() {
    	return $this->user->uid;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Eloquent implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    use Notifiable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $collection = 'users';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = '_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uid', 'id_number', 'email', 'name','nickname', 'department','sub_department', 'phone','wa_available', 
        'line_available', 'line_id', 'line_mid', 'line_group', 'line_displayname',
        'line_picture_url', 'line_picture_filename','linebot_state', 'linebot_mute','linebot_prev_state', 
        'role', 'pref_role', 'point', 'remaining_trip', 'finished_trip','vote_reward', 'referrer_uid','gender', 
        'created_at'
    ];

    public function getProfilePictureAttribute() {
        return \Config::get('constants.dropbox_base_url').$this->line_picture_filename.'_thumb.jpg';
    }
}

app/Http/Controllers/AuthUser/AuthUserController.php
<?php

namespace App\Http\Controllers\AuthUser;

use App\AuthUser;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthUserController extends Controller
{
    public function store(Request $request)
    {
        // Create Auth User
        $user = AuthUser::createAuthUser($request['name'], $request['email'], $request['privilage'], $request['password']);

    	return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Conversation/ConversationController.php
<?php

namespace App\Http\Controllers\Conversation;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\LinebotLog;
use MongoDB\BSON\Regex as MongoRegex;

class ConversationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index() {
    	$path  = 'conversations';

        $messages = [];

    	$threads = LinebotLog::with('User')
                ->where('message.text','regexp', new MongoRegex('.*Maaf respon*.'))
                ->orderBy('created_at', 'desc')
    			->take(10)
                ->get();
        //return $threads[0];
    	return view('conversations.index', compact('path', 'threads', 'messages'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\AuthUser;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $path = 'auth-user';
        $users = AuthUser::all();
        
        return view('auth_users.index', compact('path', 'users'));                
    }
    
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $path = 'users';
        $users = User::all();
        
        return view('users.index', compact('path', 'users'));                
    }

    public function detail($uid)
    {
        $path  = 'users-detail';
        $user = User::where('uid',$uid)->get();

        return view('users.detail', compact('path','user'));                                
    }
}

resources/views/admin/page-title.blade.php
<div class="container">
    <div class="row">
        <div class="col lg-12">
            <div class="page-title">
                <div class="pull-left"><h1>{{ $pageTitle ? $pageTitle : 'No Page Title' }}</h1></div>
                <div class="pull-right">
                    <ol class="breadcrumb">
                        <li><a href="/"><i class="fa fa-home"></i> &nbsp;Home</a></li>
                        <li class="active"><strong>{{ $pageTitle ? $pageTitle : 'Breadcrumb End' }}</strong></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/auth_users/index.blade.php
@extends('layouts.admin.master')

@section('content')

    @include('admin.page-title',['pageTitle' => 'Users'])

    <div class="container">
        <div class="row">
            <div class="col lg-12">
                <section class="box">
                    <header class="box-header info">
                        <h2 class="box-header-title pull-left">User Management</h2>
                    </header>

                    <!-- Show User -->
                    <main class="box-content">
                    <div class="row mt-0">
                        <div class="col lg-8">
                            <div class="responsive-table-wrap">
                                <table class="table responsive">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Privilage</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($users as $user)
                                    <tr>
                                        <td>{{ $user-> name }}</td>
                                        <td>{{ $user-> email }}</td>
                                        <td>{{ $user-> privilage }}</td>
                                    </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                        </div>
                    </div>
                    </main>

                    <!-- Create New User -->
                    @if(Auth::user()->privilage === 'Admin')
                    <form role="form" action="user/store" method="POST">
                        <div class="row">
                            <div class="col lg-3">
                                <a href="#" data-modal-id="modal-1" class="btn btn-primary modal-button">Create New User</a>
                                    <div id="modal-1" class="modal">
                                        <div class="dialog">

                                            <div class="heading">
                                                <a class="close" href="#" data-close-modal><i class="mdi mdi-window-close"></i></a>
                                            </div>

                                            <div class="body">
                                                    {{ csrf_field() }}

                                                    <p>Name</p>
                                                    <input name="name" type="text" class="form-control lg" placeholder="Name..." required autofocus>

                                                    <p>Email</p>
                                                    <input type="email" name="email" class="form-control lg" placeholder="Email...">

                                                    <p>Privilage</p>
                                                    <div class="form-group">
                                                        <select name="privilage" id="select-form-1" class="form-control md">
                                                            <option value="Admin">Admin</option>
                                                            <option value="Default">Default</option>
                                                        </select>
                                                    </div>

                                                    <p>Password</p>
                                                    <input name="password" type="password" class="form-control lg" placeholder="Password..." required>
                                            </div>

                                            <div class="footer">
                                                <div class="pull-right">
                                                    <button type="submit" class="btn md primary ml-10">REGISTER</button>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                        </div>
                    </form>
                    @endif

                </section>
            </div>
        </div>
    </div>

@endsection

resources/views/conversations/chat.blade.php
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
      <meta name="csrf-token" content="{{csrf_token()}}">
    <title>Talk Message</title>
    
    
    <link rel="stylesheet" href="{{asset('chat/css/reset.css')}}">

    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>

        <link rel="stylesheet" href="{{asset('chat/css/style.css')}}">

    
    
    
  </head>

  <body>
<div class="header">
    <div class="container header-brand">
        <a href="{{url('/home')}}" class="brand">Talk Message</a>
    </div>
</div>
  <div class="container clearfix body">
   @include('partials.peoplelist')
    
    <div class="chat">
      <div class="chat-header clearfix">
        @if(isset($user))
            <img src="{{@$user->avatar}}" alt="avatar" />
        @endif
        <div class="chat-about">
            @if(isset($user))
                <div class="chat-with">{{'Chat with ' . @$user->name}}</div>
            @else
                <div class="chat-with">No Thread Selected</div>
            @endif
        </div>
        <i class="fa fa-star"></i>
      </div> <!-- end chat-header -->
      
      @yield('content')
      
      <div class="chat-message clearfix">
      <form action="" method="post" id="talkSendMessage">
            <textarea name="message-data" id="message-data" placeholder ="Type your message" rows="3"></textarea>
            <input type="hidden" name="_id" value="{{@request()->route('id')}}">
            <button type="submit">Send</button>
      </form>

      </div> <!-- end chat-message -->
      
    </div> <!-- end chat -->
    
  </div> <!-- end container -->


      <script>
          var __baseUrl = "{{url('/')}}"
      </script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js'></script>



        <script src="{{asset('chat/js/talk.js')}}"></script>

    <script>
        var show = function(data) {
            alert(data.sender.name + " - '" + data.message + "'");
        }

        var msgshow = function(data) {
            var html = '<li id="message-' + data.id + '">' +
            '<div class="message-data">' +
            '<span class="message-data-name"> <a href="#" class="talkDeleteMessage" data-message-id="' + data.id + '" title="Delete Messag"><i class="fa fa-close" style="margin-right: 3px;"></i></a>' + data.sender.name + '</span>' +
            '<span class="message-data-time">1 Second ago</span>' +
            '</div>' +
            '<div class="message my-message">' +
            data.message +
            '</div>' +
            '</li>';

            $('#talkMessages').append(html);
        }

    </script>

  </body>
</html>

resources/views/conversations/index.blade.php
@extends('layouts.admin.master')

@section('header')
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
<link rel="stylesheet" href="{{asset('chat/css/style.css')}}">
@endsection

@section('content')
	<main class="box-content">
	<div class="container clearfix body">
   @include('conversations.partials.peoplelist')
    
    <div class="chat">
      <div class="chat-header clearfix">
        @if(isset($user))
            <img src="{{@$user->avatar}}" alt="avatar" />
        @endif
        <div class="chat-about">
            @if(isset($user))
                <div class="chat-with">{{'Chat with ' . @$user->name}}</div>
            @else
                <div class="chat-with">No Thread Selected</div>
            @endif
        </div>
        <i class="fa fa-star"></i>
      </div> <!-- end chat-header -->
      
      <div class="chat-history">
        <ul id="talkMessages">

            @foreach($messages as $message)
                @if($message->sender->id == auth()->user()->id)
                    <li class="clearfix" id="message-{{$message->id}}">
                        <div class="message-data align-right">
                            <span class="message-data-time" >{{$message->humans_time}} ago</span> &nbsp; &nbsp;
                            <span class="message-data-name" >{{$message->sender->name}}</span>
                            <a href="#" class="talkDeleteMessage" data-message-id="{{$message->id}}" title="Delete Message"><i class="fa fa-close"></i></a>
                        </div>
                        <div class="message other-message float-right">
                            {{$message->message}}
                        </div>
                    </li>
                @else

                    <li id="message-{{$message->id}}">
                        <div class="message-data">
                            <span class="message-data-name"> <a href="#" class="talkDeleteMessage" data-message-id="{{$message->id}}" title="Delete Messag"><i class="fa fa-close" style="margin-right: 3px;"></i></a>{{$message->sender->name}}</span>
                            <span class="message-data-time">{{$message->humans_time}} ago</span>
                        </div>
                        <div class="message my-message">
                            {{$message->message}}
                        </div>
                    </li>
                @endif
            @endforeach


        </ul>

    </div> <!-- end chat-history -->
      
      <div class="chat-message clearfix">
      <form action="" method="post" id="talkSendMessage">
            <textarea name="message-data" id="message-data" placeholder ="Type your message" rows="3"></textarea>
            <input type="hidden" name="_id" value="{{@request()->route('id')}}">
            <button type="submit">Send</button>
      </form>

      </div> <!-- end chat-message -->
      
    </div> <!-- end chat -->
    
  </div> <!-- end container -->
</main>

@endsection

resources/views/conversations/messages/conversations.blade.php
@extends('layouts.chat')

@section('content')
    <div class="chat-history">
        <ul id="talkMessages">

            @foreach($messages as $message)
                @if($message->sender->id == auth()->user()->id)
                    <li class="clearfix" id="message-{{$message->id}}">
                        <div class="message-data align-right">
                            <span class="message-data-time" >{{$message->humans_time}} ago</span> &nbsp; &nbsp;
                            <span class="message-data-name" >{{$message->sender->name}}</span>
                            <a href="#" class="talkDeleteMessage" data-message-id="{{$message->id}}" title="Delete Message"><i class="fa fa-close"></i></a>
                        </div>
                        <div class="message other-message float-right">
                            {{$message->message}}
                        </div>
                    </li>
                @else

                    <li id="message-{{$message->id}}">
                        <div class="message-data">
                            <span class="message-data-name"> <a href="#" class="talkDeleteMessage" data-message-id="{{$message->id}}" title="Delete Messag"><i class="fa fa-close" style="margin-right: 3px;"></i></a>{{$message->sender->name}}</span>
                            <span class="message-data-time">{{$message->humans_time}} ago</span>
                        </div>
                        <div class="message my-message">
                            {{$message->message}}
                        </div>
                    </li>
                @endif
            @endforeach


        </ul>

    </div> <!-- end chat-history -->

@endsection

resources/views/conversations/partials/chathistory.blade.php
<div class="chat-history">
    <ul>
        <li class="clearfix">
            <div class="message-data align-right">
                <span class="message-data-time" >10:10 AM, Today</span> &nbsp; &nbsp;
                <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>

            </div>
            <div class="message other-message float-right">
                Hi Vincent, how are you? How is the project coming along?
            </div>
        </li>

        <li>
            <div class="message-data">
                <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
                <span class="message-data-time">10:12 AM, Today</span>
            </div>
            <div class="message my-message">
                Are we meeting today? Project has been already finished and I have results to show you.
            </div>
        </li>

        <li class="clearfix">
            <div class="message-data align-right">
                <span class="message-data-time" >10:14 AM, Today</span> &nbsp; &nbsp;
                <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>

            </div>
            <div class="message other-message float-right">
                Well I am not sure. The rest of the team is not here yet. Maybe in an hour or so? Have you faced any problems at the last phase of the project?
            </div>
        </li>

        <li>
            <div class="message-data">
                <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
                <span class="message-data-time">10:20 AM, Today</span>
            </div>
            <div class="message my-message">
                Actually everything was fine. I'm very excited to show this to our team.
            </div>
        </li>

        <li>
            <div class="message-data">
                <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
                <span class="message-data-time">10:31 AM, Today</span>
            </div>
            <i class="fa fa-circle online"></i>
            <i class="fa fa-circle online" style="color: #AED2A6"></i>
            <i class="fa fa-circle online" style="color:#DAE9DA"></i>
        </li>

    </ul>

</div> <!-- end chat-history -->

resources/views/conversations/partials/peoplelist.blade.php
<div class="people-list" id="people-list">
    <div class="search" style="text-align: center">
        <a href="{{url('/home')}}" style="font-size:16px; text-decoration:none; color: white;"><i class="fa fa-user"></i> {{auth()->user()->name}}</a>
    </div>
    <ul class="list">
        @foreach($threads as $inbox)
            @if(!is_null($inbox->message['text']))
        <li class="clearfix">
            <a href="#">
            <img src="{{ $inbox->user->profile_picture }}" alt="avatar" />
            <div class="about">
                <div class="name">{{$inbox->user->name}}</div>
                <div class="status">
                    <span class="fa fa-reply"></span>
                    <span>{{substr($inbox->message['text'], 0, 20)}}</span>
                </div>
            </div>
            </a>
        </li>
            @endif
        @endforeach

    </ul>
</div>

resources/views/layouts/admin/auth-master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta id="csrfToken" name="_token" content="{{ csrf_token() }}">
    <title>Laravel+</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:100,400,300,500,600,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:100,400,300,600,700">
    <link rel="stylesheet" href="{{ asset('css/admin.css') }}">
    <script>
        window.LaravelPlus = window.LaravelPlus || {};
        window.LaravelPlus.csrfToken = "{{ csrf_token() }}";
    </script>
</head>
<body class="@yield('body-class')">

<div id="admin" class="admin @yield('adminBodyClass')">

    @yield('content')

</div>

<script src="{{ asset('js/admin.js') }}"></script>
</body>
</html>

resources/views/layouts/admin/main-menu.blade.php
<div id="main-menu" class="main-menu">
    <div class="main-menu-profile-row">
        <div class="main-menu-profile-img">
            <a href="/"><img src="{{ asset('images/users/1.png') }}" alt=""></a>
        </div>

        <div class="main-menu-profile-info">
            <h5 class="title"><a href="/">{{ Auth::user()->name }}</a></h5>
            <p class="role">{{ Auth::user()->privilage }}</p>
            
            <!-- Logout -->
            <a href="{{ url('/logout') }}"
                onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                <p>Logout</p>
            </a>
            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
            </form>
        </div>
    </div>

    <div class="main-menu-links-row">
        <ul id="main-menu" class="main-menu perform-menu">
            <li class="{{ adminMenuClass('auth-user', $path) }}">
                <a href="{{ route('auth-user') }}">
                    <i class="fa fa-user"></i> Auth User Management
                </a>
            </li>
            <li class="{{ adminMenuClass('users', $path) }}">
                <a href="{{ route('users') }}">
                    <i class="fa fa-users"></i> Users
                </a>
            </li>
            <li class="{{ adminMenuClass('conversations', $path) }}">
                <a href="{{ route('conversations') }}">
                    <i class="fa fa-wechat"></i> Conversations   
                </a>
            </li>
         </ul>
    </div>
</div>

resources/views/layouts/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta id="csrfToken" name="_token" content="{{ csrf_token() }}">
    <title>DUGONG</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:100,400,300,500,600,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:100,400,300,600,700">
    <link rel="stylesheet" href="{{ asset('css/admin.css') }}">
    <script>
        window.LaravelPlus = window.LaravelPlus || {};
        window.LaravelPlus.csrfToken = "{{ csrf_token() }}";
    </script>
    @yield('header')
</head>
<body class="@yield('body-class')">

<div id="admin" class="admin">

    @include('layouts.admin.top-bar')

    <div id="main-menu-wrap" class="main-menu-wrap">
        @include('layouts.admin.main-menu')
    </div>

    <div class="content-wrap">
        <div id="content" class="content">
            @yield('content')
        </div>
    </div>

</div>

<script src="{{ asset('js/admin.js') }}"></script>
</body>
</html>

resources/views/layouts/admin/top-bar.blade.php
<div id="top-bar" class="top-bar">
    <div class="top-bar-logo-wrap">
        <a href="/" class="logo">
            <h1>Dugong</h1>
        </a>
    </div>
    <ul class="top-nav pull-right-below-l">
        <li><a href="#" data-button="top-menu-search" data-container-id="top-menu-search"><i class="mdi mdi-magnify"></i></a></li>
        <li><a id="main-menu-toggle" href="/"><i class="mdi mdi-menu"></i></a></li>
    </ul>
    <div id="top-menu-search" class="top-bar-search">
        <div class="search-form clearfix">
            <form action="">
                <div class="input-group justify">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        <input name="s" type="search" class="form-control" placeholder="Search something...">
                    </div>
                    <div class="input-group search">
                        <button type="submit" class="button primary" data-dropdown="toggle-button">Search</button>
                    </div>
                    <div class="input-group close">
                        <a type="submit" class="close-search button primary p-0 plain" data-dropdown="toggle-button"><i class="mdi mdi-close"></i></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>